### ISSUE TITLE
Sync Command Discussion

### ISSUE THREAD

**Issue by alexraskin** [KOOKIIEStudios/PalCON-Discord#10]
I was curious on your thoughts of using a normal command for this? (!sync) style

Or would you like something passed during the start of the bot?

Thanks

**Comment by Bratah123** [comment]
I actually left a [comment](https://github.com/KOOKIIEStudios/PalCON-Discord/pull/8#issuecomment-1921821451) on the pull request, I don't think you saw. But I'm okay with making it a non-slash command!
