### ISSUE TITLE
Bot on integration page? Need help pls

### ISSUE THREAD

**Issue by BloodDragon2580** [KOOKIIEStudios/PalCON-Discord#12]
How can I add the bot to the integration page in discord? So that only certain commands are available to normal users? It would be nice if someone could explain this to me.

**Comment by KOOKIIEStudios** [comment]
Most of the commands require server admin perms. Only `/info` and `/online` can be used without admin perms.

This is coded in `main.py` via the `@has_permissions(administrator=True)` decorator in each command

**Comment by BloodDragon2580** [comment]
I saw it, that's why I closed the topic. Thanks for the answer anyway ^^.
