### ISSUE TITLE
[BUG] Unable to parse player info for player

### ISSUE THREAD

**Issue by BloodDragon2580** [KOOKIIEStudios/PalCON-Discord#13]
**Describe the bug**

When i use the command **"/online"** every time is 0 Players Online, and in the console this error is showing:
**"Unable to parse player info for player"**

> 2024-02-02 13:29:59,574 - client - INFO - Setting up RCON connection
> 2024-02-02 13:29:59,579 - client - DEBUG - Fetching online players
> 2024-02-02 13:29:59,702 - client - ERROR - Unable to parse player info for player: ['Order', '24XXXXXXX5681']

**Desktop (please complete the following information):**
 **- OS: Windows 2019
 - Version: Latest Build** https://github.com/KOOKIIEStudios/PalCON-Discord/commit/c0f085a542b7490000e84c771a9ad9d269f482d2

**Comment by Bratah123** [comment]
Thanks, those are the logs I needed to see. Seems like pal world will sometimes not have a playerID for players.

Is the 2nd item in ['Order', '24XXXXXXX5681'] 17 digits long (24XXXXXXX5681) in the logs? if so that indicates the steam id

**Comment by BloodDragon2580** [comment]
I didn't post the entire Steam ID. I put the XXXXXXX in. But I can post the correct steam id. If you need them.

**Comment by Bratah123** [comment]
> I didn't post the entire Steam ID. I put the XXXXXXX in. But I can post the correct steam id. If you need them.

That would greatly help me thanks!

**Comment by BloodDragon2580** [comment]
```
2024-02-02 13:29:59,574 - client - INFO - Setting up RCON connection
2024-02-02 13:29:59,579 - client - DEBUG - Fetching online players
2024-02-02 13:29:59,702 - client - ERROR - Unable to parse player info for player: ['Order', '2429775681']
```

**Comment by Bratah123** [comment]
@BloodDragon2580 Added some logic fixes in 88d0285ed0aa83f0d87d283924e0b0ac205a6480

should fix the 0 players online, but you might run into some issues that will be logged, lmk ASAP what the logs are as I try to pinpoint why this issue might occur thanks!

**Comment by BloodDragon2580** [comment]
It worked now thx for the fix.

**Comment by Bratah123** [comment]
Great thanks! Shall an issue arrive again, feel free to open another issue. For now I'm closing this!
