### ISSUE TITLE
[BUG] ModuleNotFoundError: No module named 'discord'

### ISSUE THREAD

**Issue by ssw1279** [KOOKIIEStudios/PalCON-Discord#3]
You have selected A: Virtual Python Environment
Traceback (most recent call last):
  File "C:\Users\MY COM\PycharmProjects\PalCON-Discord\main.py", line 3, in <module>
    import discord
ModuleNotFoundError: No module named 'discord'
 

The Python version is 3.11
i run start.bat, get the same error as above.
Is it a problem if I use a language other than English for config?

**Comment by Bratah123** [comment]
Seems like your venv file did not properly download?

Can you try the command : `venv\scripts\activate.bat` in the root directory of the project (This enters you into the python virtual environment which I assume was generated when you ran `start.bat`)

And then enter `pip install -r requirements.txt` and let me know if the bot works after that.

Your project should have a venv created like this:
![image](https://github.com/KOOKIIEStudios/PalCON-Discord/assets/58405975/7bc4c3a3-49b9-45c1-b502-0a8b85af80bc)

**Comment by ssw1279** [comment]
![Screenshot 2024-02-01 at 14 30 06](https://github.com/KOOKIIEStudios/PalCON-Discord/assets/158426749/34b481a1-8ea8-439b-96e2-20dbdc5d4704)

It has been created. If it seems to be a 3.12 version problem, the same problem will be issued even if it is deleted and only 3.11 version is laid out.

**Comment by ssw1279** [comment]
ok good work . 

my work thx.

**Comment by Bratah123** [comment]
> ok good work .
> 
> my work thx.

I will take it that you managed to fix the problem.
If you could document what you did here it would be great for future users, in the mean time I will close this issue thanks!

**Comment by ssw1279** [comment]
Found another problem. Can I comment here?

**Comment by Bratah123** [comment]
> Found another problem. Can I comment here?

I prefer if you open up another issue post!

**Comment by ShadyGame** [comment]
when i run python.exe -m pip install --upgrade pip i get this error at the end
`        [^1]: For Python, any directory (with suitable naming) can be imported,
                    even if it does not contain any `.py` files.
                    On the other hand, currently there is no concept of package data
                    directory, all directories are treated like packages.
              ********************************************************************************

      !!
        check.warn(importable)
      copying multidict\__init__.pyi -> build\lib.win-amd64-cpython-312\multidict
      copying multidict\py.typed -> build\lib.win-amd64-cpython-312\multidict
      running build_ext
      building 'multidict._multidict' extension
      error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for multidict
Failed to build multidict
ERROR: Could not build wheels for multidict, which is required to install pyproject.toml-based projects`
